<!doctype html>
<html class="no-js">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<title><?php echo $page->title; ?></title>
		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />

		<!-- Place favicon.ico and apple-touch-icon(s) in the root directory -->

		<link rel="stylesheet" href="<?php echo $config->urls->templates; ?>css/normalize.css" />
		<link rel="stylesheet" href="<?php echo $config->urls->templates; ?>css/main.css" />
		<script src="<?php echo $config->urls->templates; ?>js/vendor/modernizr-2.7.1.min.js"></script>
	</head>
	<body>
		<!--[if lt IE 8]>
			<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->
		
		